title: Multiple Intelligence Survey
author: Joselle Amor
email: joselleamor24@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I'm just trying to build a website about the intelligences of the people and how they are diverse
but at the same time works together.
# social links
twitter_username:idonthavetwitte
github_username:  Joselle Amor

show_excerpts: true # set to false to remove excerpts on the homepage
